# Generated by Django 6.0.2 on 2026-03-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_updated_at_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
