# Generated by Django 6.0.1 on 2026-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='razorpay_account_id',
            field=models.CharField(blank=True, help_text='Razorpay Linked Account ID for vendors', max_length=100, null=True),
        ),
    ]
